swagger: "2.0"
info:
  version: "1.0.0"
  title: Reactive Feign API
  description: The API for the Reactive Feign

paths:
  /stream:
    get:
      description: Get All Customer
      parameters:
      responses:
        '200':
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'

definitions:
  Customer:
    type: object
    properties:
      id:
        type: string
        example: 1
      name:
        type: string
        example: Hitesh